---
title: "About"
---

## More About Me

I'm a computational biologist and a self-taught coder who works primarily in R on a daily basis (but also python when needed).

My specialties include transcriptomics, epigenomics, applying statistics, and network analysis. I am also beginning to explore the use of AI/ML natural language processing tools for large sequencing data sets.

### My focus areas include:

-   Next generation sequencing data analysis

    -   RNAseq, ATACseq, single-cell sequencing, whole-genome sequencing

-   Designing or maintaining bioinformatic pipelines

-   Data Visualization

    -   All things ggplot...trying my hand at a little Javascript/Observable/D3 recently

-   Applying biological know-how to design good questions for large complex data analysis

-   Gene regulatory network analysis

-   Epigenetics

-   Autoimmune disease and B cell tolerance mechanisms

### Resume

[See my resume](resume.pdf)


### Other interests

- Blues/jazz guitar

- Science fiction

- Craft beer
